# Site settings
title: AboutMe
email: myemail@domain.com
url: https://lxxjl.github.io
description: "Write an awesome description for your new site here."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Jason

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: https://lxxjl.github.io/

# Build settings
markdown: kramdown
permalink: pretty
