# Site settings
title: Jaylon’s Homepage
email: Jaylon@myhomepage.xyz
url: https://lxxjl.github.io
description: "Hi! I am Jaylon, welcome to my homepage~"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Jaylon

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: https://lxxjl.github.io/

# Build settings
markdown: kramdown
permalink: pretty
